# Generated by Django 3.2.9 on 2021-12-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-creation_date'], 'verbose_name_plural': 'quizzes'},
        ),
    ]
